In [3]:
import pandas as pd
import numpy as np

In [5]:
#create sample messy employee data

data = {
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        "  Alice Johnson  ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM  davis", "Jane Miller", "Chris taylor"
    ],
     "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate": [
        "2021/04/12", "2020/11/01", "2022/01/18", "2019/9/25", "2018/07/05",
        "2021/10/14", "2019/12/01", "2020/03/22", "2021/05/10", "2022/02/05"
    ],
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
    "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [6]:
df = pd.DataFrame(data)

df.to_csv("employee_dataset" , index=False)

df = pd.read_csv("employee_dataset")

df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [7]:
#get the data frame
df.shape

(10, 8)

In [8]:
#get the information of the dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      str
 2   Dept         9 non-null      str
 3   Age          9 non-null      str
 4   Salary($)    9 non-null      str
 5   JoinDate     10 non-null     str
 6   Performance  9 non-null      str
 7   Remote?      9 non-null      str
dtypes: int64(1), str(7)
memory usage: 772.0 bytes

In [9]:
#get first five row nof a dataset

df.head(3)

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y

In [10]:
#get columns for data set

df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='str')

In [11]:
#get missing value

df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [12]:
# get uniqueness of the value

print(df["Dept"].unique())
print(df["Age"].unique())
print(df["Remote?"].unique())

<StringArray>
['IT', 'hr', 'Mktng', 'Customer Care', 'marketing', 'Finance', nan, 'HR']
Length: 8, dtype: str
<StringArray>
['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']
Length: 10, dtype: str
<StringArray>
['Yes', 'No', 'Y', 'N', 'yes', 'no', nan, 'True']
Length: 8, dtype: str

In [13]:
#accesss sesries data

df["Salary($)"].tolist()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [14]:
df["fullName"].tolist()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [15]:
df["Salary($)"].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: str

In [16]:
# stat cleaning inconsistent value
#rename inconsistent column

df.columns
df.rename(columns = {
    "EmpId": "Emp_id",
    "fullName": "Full_name", 
    "Dept": "Department",
    "Age": "age",
"Salary($)": "salary",
"JoinDate": "join_date",
"Performance": "perfoemance",
"Remote?": "remote",
}, inplace=True)

df

,Emp_id,Full_name,Department,age,salary,join_date,perfoemance,remote
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [17]:
df["full_name"] = df["Full_name"].str.strip()
df["full_name"] = df["Full_name"].str.title()
df["full_name"] = df["Full_name"].str.replace(r"\s+", " ", regex=True)
df["full_name"] = df["Full_name"].str.replace(r"-" , " ")
df["full_name"].tolist()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [18]:
#clean inconsistent value

df["Department"].replace({
    "hr":"HR",
    "Mktng": "Marketing",
    "marketing": "Marketing"
    
 }, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3624\3373733420.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Department"].replace({

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7              NaN
8               HR
9        Marketing
Name: Department, dtype: str

In [19]:
#clean age

def clean_age(value):
    if value == "thirty-five":
        return 35
    elif isinstance(value, (int, float)):
       return value
    elif isinstance(value, str) and value.isdigit():
       return int(value)
    else : 
          return np.man

df["age"] = df["age"].apply(clean_age) 

df["age"]

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: age, dtype: float64

In [25]:
#clean inconsistent salary

df["salary"] = (
    df["salary"]
    .astype(str)
    .replace(r"[$ , ]", "" , regex=True)
    .replace("NAN", np.nan)
    .astype(float)
)

df["salary"].unique()

array([5500.5 , 4800.  , 4200.75,     nan, 6100.  , 4300.  , 5800.  ,
       5000.  , 4700.  , 4400.  ])