In [1]:
import pandas as pd
import numpy as np

In [2]:
#create sample messy employee data

data = {
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        "  Alice Johnson  ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM  davis", "Jane Miller", "Chris taylor"
    ],
     "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate": [
        "2021/04/12", "2020/11/01", "2022/01/18", "2019/9/25", "2018/07/05",
        "2021/10/14", "2019/12/01", "2020/03/22", "2021/05/10", "2022/02/05"
    ],
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
    "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [3]:
df = pd.DataFrame(data)

df.to_csv("employee_dataset.csv" , index=False)

df = pd.read_csv("employee_dataset.csv")

df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [4]:
#get the data frame
df.shape

(10, 8)

In [5]:
#get the information of the dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      str
 2   Dept         9 non-null      str
 3   Age          9 non-null      str
 4   Salary($)    9 non-null      str
 5   JoinDate     10 non-null     str
 6   Performance  9 non-null      str
 7   Remote?      9 non-null      str
dtypes: int64(1), str(7)
memory usage: 772.0 bytes

In [6]:
#get first five row nof a dataset

df.head(3)

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y

In [7]:
#get columns for data set

df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='str')

In [8]:
#get missing value

df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [9]:
# get uniqueness of the value

print(df["Dept"].unique())
print(df["Age"].unique())
print(df["Remote?"].unique())

<StringArray>
['IT', 'hr', 'Mktng', 'Customer Care', 'marketing', 'Finance', nan, 'HR']
Length: 8, dtype: str
<StringArray>
['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']
Length: 10, dtype: str
<StringArray>
['Yes', 'No', 'Y', 'N', 'yes', 'no', nan, 'True']
Length: 8, dtype: str

In [10]:
#accesss sesries data

df["Salary($)"].tolist()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [11]:
df["fullName"].tolist()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [12]:
df["Salary($)"].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: str

In [13]:
# stat cleaning inconsistent value

#rename inconsistent column

df.columns
df.rename(columns = {
    "EmpId": "Emp_id",
    "fullName": "Full_name", 
    "Dept": "Department",
    "Age": "age",
"Salary($)": "salary",
"JoinDate": "join_date",
"Performance": "performance",
"Remote?": "remote",
}, inplace=True)

df

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,2021/04/12,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020/11/01,73,No
2,103,sarah lee,Mktng,26,4200.75,2022/01/18,90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,2018/07/05,82,yes
5,106,john brown,marketing,27,"4,300",2021/10/14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020/03/22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,2021/05/10,79%,NaN
9,110,Chris taylor,marketing,28,4400,2022/02/05,91,True

In [14]:
df["full_name"] = df["Full_name"].str.strip()
df["full_name"] = df["Full_name"].str.title()
df["full_name"] = df["Full_name"].str.replace(r"\s+", " ", regex=True)
df["full_name"] = df["Full_name"].str.replace(r"-" , " ")
df["full_name"].tolist()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [15]:
#clean inconsistent value

df["Department"] = df["Department"].replace({
    "hr":"HR",
    "Mktng": "Marketing",
    "marketing": "Marketing"
    
 }, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_3136\2364934338.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Department"] = df["Department"].replace({

In [16]:
#clean age

def clean_age(value):
    if value == "thirty-five":
        return 35
    elif isinstance(value, (int, float)):
       return value
    elif isinstance(value, str) and value.isdigit():
       return int(value)
    else : 
          return np.man

df["age"] = df["age"].apply(clean_age) 

df["age"]

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: age, dtype: float64

In [17]:
#clean inconsistent salary

df["salary"] = (
    df["salary"]
    .astype(str)
    .replace(r"[$ , ]", "" , regex=True)
    .replace("NAN", np.nan)
    .astype(float)
)

df["salary"].unique()

array([5500.5 , 4800.  , 4200.75,     nan, 6100.  , 4300.  , 5800.  ,
       5000.  , 4700.  , 4400.  ])

In [18]:
df["join_date"] = pd.to_datetime(df["join_date"] , errors = "coerce")
df["join_date"]

0   2021-04-12
1   2020-11-01
2   2022-01-18
3   2019-09-25
4   2018-07-05
5   2021-10-14
6   2019-12-01
7   2020-03-22
8   2021-05-10
9   2022-02-05
Name: join_date, dtype: datetime64[us]

In [19]:
#clean inconsistent value in performance

df["performance"] = (
    df["performance"]
    .astype(str)
    .str.replace("%"," ", regex=False)
    .replace("None", np.nan)
    .astype(float)
    )

df["performance"]

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7     NaN
8    79.0
9    91.0
Name: performance, dtype: float64

In [20]:
#clean inconsistent value on remote

df["remote"].replace({
    "Y": "Yes",
    "N": "No",
    "no": "No",
    "True": "Yes",
    "yes": "Yes",
    None: np.nan
}, inplace=True)

df

C:\Users\HP\AppData\Local\Temp\ipykernel_3136\1964137397.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["remote"].replace({

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee
3,104,David-Kim,IT,31.0,NaN,2019-09-25,65.0,N,David Kim
4,105,NaN,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson
7,108,TOM davis,NaN,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis
8,109,Jane Miller,HR,NaN,4700.00,2021-05-10,79.0,NaN,Jane Miller
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor

In [21]:
#make all number both string and int all numerical

df["Emp_id"] = pd.to_numeric(df["Emp_id"], errors="coerce")
df["Emp_id"]

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: Emp_id, dtype: int64

In [22]:
df

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee
3,104,David-Kim,IT,31.0,NaN,2019-09-25,65.0,N,David Kim
4,105,NaN,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson
7,108,TOM davis,NaN,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis
8,109,Jane Miller,HR,NaN,4700.00,2021-05-10,79.0,NaN,Jane Miller
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor

In [23]:
#Handling missing valueby replacing nan with unknown 
df["Full_name"] = df["Full_name"].fillna("unknown")
df["Full_name"]

0      Alice Johnson
1        MICHEAL smith
2            sarah lee
3            David-Kim
4              unknown
5           john brown
6          Emma Wilson
7           TOM  davis
8          Jane Miller
9         Chris taylor
Name: Full_name, dtype: str

In [24]:
df

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee
3,104,David-Kim,IT,31.0,NaN,2019-09-25,65.0,N,David Kim
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson
7,108,TOM davis,NaN,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis
8,109,Jane Miller,HR,NaN,4700.00,2021-05-10,79.0,NaN,Jane Miller
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor

In [25]:
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])
df["Department"]

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7        Marketing
8               HR
9        Marketing
Name: Department, dtype: str

In [26]:
df

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee
3,104,David-Kim,IT,31.0,NaN,2019-09-25,65.0,N,David Kim
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis
8,109,Jane Miller,HR,NaN,4700.00,2021-05-10,79.0,NaN,Jane Miller
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor

In [27]:
df["age"] = df["age"].fillna(df["age"].median())
df["age"]

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8    30.0
9    28.0
Name: age, dtype: float64

In [28]:
df["salary"] = df["salary"].fillna(df["salary"].median())
df["salary"]

0    5500.50
1    4800.00
2    4200.75
3    4800.00
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [29]:
df["perfoemance"] = df["performance"].fillna(df["performance"].median())
df["performance"]

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7     NaN
8    79.0
9    91.0
Name: performance, dtype: float64

In [30]:
df["remote"] = df["remote"].fillna(df["remote"].mode())
df["remote"]

0     Yes
1      No
2       Y
3       N
4     yes
5      no
6       Y
7     Yes
8     NaN
9    True
Name: remote, dtype: str

In [31]:
#working with filter
df.head()

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0

In [32]:
df["Full_name"]

0      Alice Johnson
1        MICHEAL smith
2            sarah lee
3            David-Kim
4              unknown
5           john brown
6          Emma Wilson
7           TOM  davis
8          Jane Miller
9         Chris taylor
Name: Full_name, dtype: str

In [33]:
df[["Full_name","Department","salary"]]

           Full_name     Department   salary
0    Alice Johnson               IT  5500.50
1      MICHEAL smith             HR  4800.00
2          sarah lee      Marketing  4200.75
3          David-Kim             IT  4800.00
4            unknown  Customer Care  6100.00
5         john brown      Marketing  4300.00
6        Emma Wilson        Finance  5800.00
7         TOM  davis      Marketing  5000.00
8        Jane Miller             HR  4700.00
9       Chris taylor      Marketing  4400.00

In [34]:
df.iloc[0:3]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0

In [35]:
df.iloc[0:3 , 0:3]

   Emp_id          Full_name Department
0     101    Alice Johnson           IT
1     102      MICHEAL smith         HR
2     103          sarah lee  Marketing

In [36]:
df.loc[df["salary"] > 5000]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes,Alice Johnson,87.0
4,105,unknown,Customer Care,42.0,6100.0,2018-07-05,82.0,yes,NaN,82.0
6,107,Emma Wilson,Finance,33.0,5800.0,2019-12-01,88.0,Y,Emma Wilson,88.0

In [37]:
df.loc[df["salary"] > 5000,["Full_name" , "Department"]]

           Full_name     Department
0    Alice Johnson               IT
4            unknown  Customer Care
6        Emma Wilson        Finance

In [38]:
df[df["Department"]== "IT"]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes,Alice Johnson,87.0
3,104,David-Kim,IT,31.0,4800.0,2019-09-25,65.0,N,David Kim,65.0

In [39]:
df[df["age"] > 25]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,NaN,Jane Miller,79.0
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0

In [40]:
df[df["Department"] != "HR"]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0

In [41]:
df[
    (df["salary"] > 4000) & (df["remote"] == "Yes")
]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes,Alice Johnson,87.0
7,108,TOM davis,Marketing,30.0,5000.0,2020-03-22,NaN,Yes,TOM davis,82.0

In [42]:
df[
    (df["salary"] > 4000) | (df["remote"] == "Yes")
]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,NaN,Jane Miller,79.0
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0

In [43]:
df[
    df["Department"].isin(["IT", "Finance"])
]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes,Alice Johnson,87.0
3,104,David-Kim,IT,31.0,4800.0,2019-09-25,65.0,N,David Kim,65.0
6,107,Emma Wilson,Finance,33.0,5800.0,2019-12-01,88.0,Y,Emma Wilson,88.0

In [44]:
df[df["Full_name"].str.contains("john" , case=False)]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes,Alice Johnson,87.0
5,106,john brown,Marketing,27.0,4300.0,2021-10-14,75.0,no,john brown,75.0

In [45]:
df[df["Department"].str.startswith("M")]

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0

In [46]:
#sorting

df.sort_values("salary")

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,NaN,Jane Miller,79.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0

In [47]:
df.sort_values("salary" , ascending=False)

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,NaN,Jane Miller,79.0
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0

In [48]:
df.sort_values("performance" , ascending=False)

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,NaN,Jane Miller,79.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0

In [49]:
df.sort_values("performance" , ascending=False).head()

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0

In [50]:
df.sort_values(["Department","salary"], ascending=[True ,False])

,Emp_id,Full_name,Department,age,salary,join_date,performance,remote,full_name,perfoemance
4,105,unknown,Customer Care,42.0,6100.00,2018-07-05,82.0,yes,NaN,82.0
6,107,Emma Wilson,Finance,33.0,5800.00,2019-12-01,88.0,Y,Emma Wilson,88.0
1,102,MICHEAL smith,HR,35.0,4800.00,2020-11-01,73.0,No,MICHEAL smith,73.0
8,109,Jane Miller,HR,30.0,4700.00,2021-05-10,79.0,NaN,Jane Miller,79.0
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes,Alice Johnson,87.0
3,104,David-Kim,IT,31.0,4800.00,2019-09-25,65.0,N,David Kim,65.0
7,108,TOM davis,Marketing,30.0,5000.00,2020-03-22,NaN,Yes,TOM davis,82.0
9,110,Chris taylor,Marketing,28.0,4400.00,2022-02-05,91.0,True,Chris taylor,91.0
5,106,john brown,Marketing,27.0,4300.00,2021-10-14,75.0,no,john brown,75.0
2,103,sarah lee,Marketing,26.0,4200.75,2022-01-18,90.0,Y,sarah lee,90.0

In [51]:
#value count

df['Department'].value_counts()

Department
Marketing        4
IT               2
HR               2
Customer Care    1
Finance          1
Name: count, dtype: int64

In [52]:
df['Department'].value_counts(normalize=True)

Department
Marketing        0.4
IT               0.2
HR               0.2
Customer Care    0.1
Finance          0.1
Name: proportion, dtype: float64

In [53]:
df['Department'].value_counts(normalize=True)*100

Department
Marketing        40.0
IT               20.0
HR               20.0
Customer Care    10.0
Finance          10.0
Name: proportion, dtype: float64

In [54]:
df['remote'].value_counts(normalize=True)

remote
Yes     0.222222
Y       0.222222
No      0.111111
N       0.111111
yes     0.111111
no      0.111111
True    0.111111
Name: proportion, dtype: float64

In [55]:
#working with merge

data1 = {
    "department": ["IT", "HR", "Finance", "Marketing", "R&D", "Operations", "Sales", "Logistics", "Procurement", "Customer Service"],
    "manager": [
        "Tom Hanks", "Susan Lee", "Robert Miles",
        "Mark Chan", "Sarah Connor", "James Nwosu", "Adaeze Obi",
        "Daniel Smith", "Amina Yusuf", "Grace Ojo"
    ],
    "department_budget": [200000, 150000, 250000, 180000, 300000, 220000, 210000, 195000, 230000, 170000],
    "office_location": [
        "Lagos", "Abuja", "Port Harcourt", "Ibadan", "Enugu", "Kano",
        "Lagos", "Calabar", "Abuja", "Kano"
    ]
}


df1 = pd.DataFrame(data1)
df1.to_csv("department_data.csv" , index=False)
df1 = pd.read_csv("department_data.csv")
df1.head()

  department       manager  department_budget office_location
0         IT     Tom Hanks             200000           Lagos
1         HR     Susan Lee             150000           Abuja
2    Finance  Robert Miles             250000   Port Harcourt
3  Marketing     Mark Chan             180000          Ibadan
4        R&D  Sarah Connor             300000           Enugu

In [57]:
merge_df = pd.merge(df , df1 , how="inner")
merge_df

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False